### ISSUE TITLE
tsims bug(?

### ISSUE THREAD

**Issue by fixff** [jc-verse/Easy-TSIMS#1]
学长好，是不是因为 t 站现在变成.173 这个插件就无法使用了（（ thx！

http://101.230.1.173:6300/home.html

<img width="532" alt="截屏2022-08-29 13 36 56" src="https://user-images.githubusercontent.com/112372064/187130553-dbe7902b-310a-4df2-b85c-c994604bf675.png">

**Comment by kevintao0417** [comment]
> 学长好，是不是因为 t 站现在变成.173 这个插件就无法使用了（（ thx！
> 
> http://101.230.1.173:6300/home.html
> 
> <img alt="截屏2022-08-29 13 36 56" width="532" src="https://user-images.githubusercontent.com/112372064/187130553-dbe7902b-310a-4df2-b85c-c994604bf675.png">

不是的 你load unpack就可以安装的 crx不能安装是chrome的extension策略修改了

**Comment by Josh-Cena** [comment]
应该很久以前就修复了 173 的问题，如果你是 Chrome 的话，记得按照安装指南（在首页上）的要求使用 load unpacked.

现在确实有另一个警告：

<img width="706" alt="image" src="https://user-images.githubusercontent.com/55398995/191052019-8ed4838d-a30b-408d-9337-482494cd4076.png">

不过应该不影响使用。我后面有时间会研究的
